//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppA.ServiceReferenceB {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceB.IServiceB")]
    public interface IServiceB {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetData", ReplyAction="http://tempuri.org/IServiceB/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetData", ReplyAction="http://tempuri.org/IServiceB/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceB/GetDataUsingDataContractResponse")]
        WcfServiceA.ServiceReferenceB.CompositeType GetDataUsingDataContract(WcfServiceA.ServiceReferenceB.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceB/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceB/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceA.ServiceReferenceB.CompositeType> GetDataUsingDataContractAsync(WcfServiceA.ServiceReferenceB.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBChannel : ConsoleAppA.ServiceReferenceB.IServiceB, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBClient : System.ServiceModel.ClientBase<ConsoleAppA.ServiceReferenceB.IServiceB>, ConsoleAppA.ServiceReferenceB.IServiceB {
        
        public ServiceBClient() {
        }
        
        public ServiceBClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfServiceA.ServiceReferenceB.CompositeType GetDataUsingDataContract(WcfServiceA.ServiceReferenceB.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceA.ServiceReferenceB.CompositeType> GetDataUsingDataContractAsync(WcfServiceA.ServiceReferenceB.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
